export const cities = [
  {
    id: 28,
    province_id: 3,
    name: "KATHMANDU",
    Code: 306,
    children: [
      {
        id: 1545,
        name: "Kirtipur Municipality",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1546, name: "Lapsephedi", district_id: 28, parent_code: "27" },
      { id: 1547, name: "Machhegaun", district_id: 28, parent_code: "27" },
      {
        id: 1548,
        name: "Mahadevathan",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1549, name: "Mahankal", district_id: 28, parent_code: "27" },
      { id: 1550, name: "Manmaiju", district_id: 28, parent_code: "27" },
      { id: 1551, name: "Matatirtha", district_id: 28, parent_code: "27" },
      { id: 1552, name: "Mulpani", district_id: 28, parent_code: "27" },
      { id: 1553, name: "Naglebhare", district_id: 28, parent_code: "27" },
      {
        id: 1554,
        name: "Naikap Naya Bhanjyang",
        district_id: 28,
        parent_code: "27",
      },
      {
        id: 1555,
        name: "Naikap Purano Bhanjya",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1556, name: "Nayapati", district_id: 28, parent_code: "27" },
      { id: 1557, name: "Pukhulachhi", district_id: 28, parent_code: "27" },
      { id: 1558, name: "Ramkot", district_id: 28, parent_code: "27" },
      { id: 1559, name: "Sangla", district_id: 28, parent_code: "27" },
      { id: 1560, name: "Satikhel", district_id: 28, parent_code: "27" },
      { id: 1561, name: "Satungal", district_id: 28, parent_code: "27" },
      { id: 1562, name: "Seuchatar", district_id: 28, parent_code: "27" },
      {
        id: 1563,
        name: "Sheshnarayan",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1564, name: "Sitapaila", district_id: 28, parent_code: "27" },
      { id: 1565, name: "Sundarijal", district_id: 28, parent_code: "27" },
      { id: 1566, name: "Suntol", district_id: 28, parent_code: "27" },
      {
        id: 1567,
        name: "Talkududechour",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1568, name: "Thankot", district_id: 28, parent_code: "27" },
      { id: 1569, name: "Tinthana", district_id: 28, parent_code: "27" },
      {
        id: 1570,
        name: "Tokha Chandeswori",
        district_id: 28,
        parent_code: "27",
      },
      {
        id: 1571,
        name: "Tokha Sarswoti",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1572, name: "Aalapot", district_id: 28, parent_code: "27" },
      {
        id: 1573,
        name: "Baad Bhanjyang",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1574, name: "Bajrayogini", district_id: 28, parent_code: "27" },
      { id: 1575, name: "Balambu", district_id: 28, parent_code: "27" },
      { id: 1576, name: "Baluwa", district_id: 28, parent_code: "27" },
      { id: 1577, name: "Bhadrabas", district_id: 28, parent_code: "27" },
      { id: 1578, name: "Bhimdhunga", district_id: 28, parent_code: "27" },
      {
        id: 1579,
        name: "Budanilkantha",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1580, name: "Chalnakhel", district_id: 28, parent_code: "27" },
      {
        id: 1581,
        name: "Chapali Bhadrakali",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1582, name: "Chhaimale", district_id: 28, parent_code: "27" },
      {
        id: 1583,
        name: "Chouketar Dahachok",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1584, name: "Chunikhel", district_id: 28, parent_code: "27" },
      { id: 1585, name: "Daanchhi", district_id: 28, parent_code: "27" },
      { id: 1586, name: "Daxinkali", district_id: 28, parent_code: "27" },
      { id: 1587, name: "Dhapasi", district_id: 28, parent_code: "27" },
      {
        id: 1588,
        name: "Dharmasthali",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1589, name: "Futung", district_id: 28, parent_code: "27" },
      { id: 1590, name: "Gagalphedi", district_id: 28, parent_code: "27" },
      { id: 1591, name: "Gokarneswor", district_id: 28, parent_code: "27" },
      { id: 1592, name: "Goldhunga", district_id: 28, parent_code: "27" },
      { id: 1593, name: "Gonggabu", district_id: 28, parent_code: "27" },
      { id: 1594, name: "Gothatar", district_id: 28, parent_code: "27" },
      {
        id: 1595,
        name: "Ichang Narayan",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1596, name: "Indrayani", district_id: 28, parent_code: "27" },
      {
        id: 1597,
        name: "Jhormahankal",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1598, name: "Jitpurphedi", district_id: 28, parent_code: "27" },
      { id: 1599, name: "Jorpati", district_id: 28, parent_code: "27" },
      {
        id: 1600,
        name: "Kabhresthali",
        district_id: 28,
        parent_code: "27",
      },
      { id: 1601, name: "Kapan", district_id: 28, parent_code: "27" },
      {
        id: 1602,
        name: "Kathmandu Municipality",
        district_id: 28,
        parent_code: "27",
      },
      {
        id: 1603,
        name: "Khadka Bhadrakali",
        district_id: 28,
        parent_code: "27",
      },
    ],
  },
  {
    id: 29,
    province_id: 3,
    name: "BHAKTAPUR",
    Code: 307,
    children: [
      { id: 1485, name: "Bageswari", district_id: 29, parent_code: "25" },
      { id: 1486, name: "Jhaukhel", district_id: 29, parent_code: "25" },
      { id: 1487, name: "Kautunje", district_id: 29, parent_code: "25" },
      {
        id: 1488,
        name: "Madhyapur Thimi Municipality",
        district_id: 29,
        parent_code: "25",
      },
      { id: 1489, name: "Nagarkot", district_id: 29, parent_code: "25" },
      { id: 1490, name: "Nankhel", district_id: 29, parent_code: "25" },
      { id: 1491, name: "Sipadol", district_id: 29, parent_code: "25" },
      { id: 1492, name: "Sirutar", district_id: 29, parent_code: "25" },
      { id: 1493, name: "Sudal", district_id: 29, parent_code: "25" },
      { id: 1494, name: "Tathali", district_id: 29, parent_code: "25" },
      { id: 1495, name: "Balkot", district_id: 29, parent_code: "25" },
      {
        id: 1496,
        name: "Bhaktapur Municipality",
        district_id: 29,
        parent_code: "25",
      },
      {
        id: 1497,
        name: "Changunarayan",
        district_id: 29,
        parent_code: "25",
      },
      { id: 1498, name: "Chhaling", district_id: 29, parent_code: "25" },
      { id: 1499, name: "Chitapol", district_id: 29, parent_code: "25" },
      { id: 1500, name: "Dadhikot", district_id: 29, parent_code: "25" },
      { id: 1501, name: "Duwakot", district_id: 29, parent_code: "25" },
      { id: 1502, name: "Gundu", district_id: 29, parent_code: "25" },
    ],
  },
  {
    id: 30,
    province_id: 3,
    name: "LALITPUR",
    Code: 308,
    children: [
      { id: 1503, name: "Asrang", district_id: 30, parent_code: "26" },
      { id: 1504, name: "Badikhel", district_id: 30, parent_code: "26" },
      { id: 1505, name: "Bhardev", district_id: 30, parent_code: "26" },
      { id: 1506, name: "Bhattedanda", district_id: 30, parent_code: "26" },
      {
        id: 1507,
        name: "Bisankhunarayan",
        district_id: 30,
        parent_code: "26",
      },
      { id: 1508, name: "Bukhel", district_id: 30, parent_code: "26" },
      { id: 1509, name: "Bungamati", district_id: 30, parent_code: "26" },
      { id: 1510, name: "Chandanpur", district_id: 30, parent_code: "26" },
      { id: 1511, name: "Chapagaun", district_id: 30, parent_code: "26" },
      { id: 1512, name: "Chhampi", district_id: 30, parent_code: "26" },
      { id: 1513, name: "Choughare", district_id: 30, parent_code: "26" },
      { id: 1514, name: "Dalchoki", district_id: 30, parent_code: "26" },
      { id: 1515, name: "Devichour", district_id: 30, parent_code: "26" },
      { id: 1516, name: "Dhapakhel", district_id: 30, parent_code: "26" },
      { id: 1517, name: "Dhusel", district_id: 30, parent_code: "26" },
      { id: 1518, name: "Dukuchhap", district_id: 30, parent_code: "26" },
      { id: 1519, name: "Gimdi", district_id: 30, parent_code: "26" },
      { id: 1520, name: "Godamchaur", district_id: 30, parent_code: "26" },
      { id: 1521, name: "Godawari", district_id: 30, parent_code: "26" },
      { id: 1522, name: "Gotikhel", district_id: 30, parent_code: "26" },
      { id: 1523, name: "Harisiddhi", district_id: 30, parent_code: "26" },
      { id: 1524, name: "Ikudol", district_id: 30, parent_code: "26" },
      { id: 1525, name: "Imadol", district_id: 30, parent_code: "26" },
      { id: 1526, name: "Jharuwarasi", district_id: 30, parent_code: "26" },
      { id: 1527, name: "Kaleswor", district_id: 30, parent_code: "26" },
      { id: 1528, name: "Khokana", district_id: 30, parent_code: "26" },
      {
        id: 1529,
        name: "Lalitpur Municipality",
        district_id: 30,
        parent_code: "26",
      },
      { id: 1530, name: "Lamatar", district_id: 30, parent_code: "26" },
      { id: 1531, name: "Lele", district_id: 30, parent_code: "26" },
      { id: 1532, name: "Lubhu", district_id: 30, parent_code: "26" },
      { id: 1533, name: "Malta", district_id: 30, parent_code: "26" },
      { id: 1534, name: "Manikhel", district_id: 30, parent_code: "26" },
      { id: 1535, name: "Nallu", district_id: 30, parent_code: "26" },
      { id: 1536, name: "Pyutar", district_id: 30, parent_code: "26" },
      { id: 1537, name: "Sainbu", district_id: 30, parent_code: "26" },
      { id: 1538, name: "Sankhu", district_id: 30, parent_code: "26" },
      { id: 1539, name: "Sidhdipur", district_id: 30, parent_code: "26" },
      { id: 1540, name: "Sunakothi", district_id: 30, parent_code: "26" },
      { id: 1541, name: "Thaiba", district_id: 30, parent_code: "26" },
      { id: 1542, name: "Thecho", district_id: 30, parent_code: "26" },
      {
        id: 1543,
        name: "Thuladurlung",
        district_id: 30,
        parent_code: "26",
      },
      { id: 1544, name: "Tikathali", district_id: 30, parent_code: "26" },
    ],
  },
];
